apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aol0evd4p-dotnet-basic
  janus-idp.io/tekton: aol0evd4p-dotnet-basic
  backstage.io/kubernetes-id: aol0evd4p-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aol0evd4p-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
